### ISSUE TITLE
[QUESTION]: how to do composer install and a roll back feature?

### ISSUE THREAD

**Issue by itsmenewbie03** [salahhusa9/laravel-updater#47]
### What happened?

I have the following questions:
- How can I do a `composer install` for cases the latest release requires a new package?
- How can I implement a roll back feature? (is there an option where I can select which version to update to instead of just automatically updating to the latest?)

### How to reproduce the bug

This is not a bug but I can't open a question issue or anything similar.
Sorry for using this template.

### Package Version

later

### PHP Version

8.3

### Laravel Version

10.

**Comment by salahhusa9** [comment]
For composer install it's unrecommended to do inside/by package because in case of laravel-updater need also update well be a problem, i recommend running `composer install` after `php artisan updater:update`

**Comment by salahhusa9** [comment]
For question tow: 
- roll back: (not supported now) this will be probably a problem if you run migration or seeding, its depend on use case
- update to specific version not latest: this good idea

In general, i will add it

**Comment by itsmenewbie03** [comment]
> For composer install it's unrecommended to do inside/by package because in case of laravel-updater need also update well be a problem, i recommend running `composer install` after `php artisan updater:update`

so this means that running `composer install` inside 
```php
    'after_update_pipelines' => [
        // you can add your own pipelines here
    ],
```

is a bad idea?

**Comment by salahhusa9** [comment]
yes, it's bad idea
you can use this in github action for update automaticity by release

```
name: deploy to server by ssh

concurrency:
  group: production
  cancel-in-progress: true

on:
  release:
    types: [released]

# on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            php artisan updater:update
            export COMPOSER_ALLOW_SUPERUSER=1; composer install
```

as you see i run `composer install` after update.
